"""Kon. desktop application."""

from .version import (
    APP_BASE_NAME,
    APP_BRAND_NAME,
    APP_CONSOLE_LABEL,
    APP_DISPLAY_NAME,
    APP_PUBLIC_VERSION,
    APP_RELEASE_ASSET_PATTERN,
    APP_UPDATE_REPO,
    APP_VERSION,
    SETTINGS_SCHEMA_VERSION,
    STARTUP_LOGIC_VERSION,
)

__all__ = [
    "APP_BASE_NAME",
    "APP_BRAND_NAME",
    "APP_CONSOLE_LABEL",
    "APP_DISPLAY_NAME",
    "APP_PUBLIC_VERSION",
    "APP_RELEASE_ASSET_PATTERN",
    "APP_UPDATE_REPO",
    "APP_VERSION",
    "SETTINGS_SCHEMA_VERSION",
    "STARTUP_LOGIC_VERSION",
]
